### ISSUE TITLE
push individual images dmgr,node to docker hub

### ISSUE THREAD

**Issue by mmumshad** [WASdev/ci.docker.websphere-traditional#70]
Have the individual images base,dmgr,node been pushed to Docker Hub already? If not can you please push those as well? Makes it really easy to try network deployment.

**Comment by mmumshad** [comment]
Sorry, closing the issue.

**Comment by davidcurrie** [comment]
fyi: we don't have an ILAN (developer licensed) version of ND which is why there are only images for the base application server.

**Comment by mmumshad** [comment]
Thank you.  I figured so.  Also,  do you have any blog/article  reflecting the benefits  of containerizing the websphere traditional application this way.  Is this recommended on prod environment?

**Comment by davidcurrie** [comment]
We are no longer advocating running ND cells under Docker (primarily because the ND capabilities are now largely better served by a container orchestrator such as Docker EE or Kubernetes). Running single server (base) WAS traditional is still tolerated (although our preference would be to migrate to WebSphere Liberty).
